print("Subtract")
print("Hello")
print("new build")
print("hey")
print("hi")
print("My name is Krishna Sharma")
print("Ed Sheeran")
print("+*/=-")
print("5/5")
print("test")
print("helllo!!!!")
print("Welcome to ITBD02")