name: Lint Django Codebase

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Django Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install black pylint

      - name: Lint Django Codebase
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_PYLINT: true
          PYTHON_BLACK_LINE_LENGTH: 120
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
